services:
  bot:
    build: .
    restart: unless-stopped
    ports:
      - '1488:1488'
    volumes:
      - .:/app/project
      - /app/.venv
    environment:
      - SECRET_KEY=QB8RCf]yejc-LCZ8miN?g]$x+@+g1H
